### ISSUE TITLE
License

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#10]
I need someone to walk me through the pros and cons of each license.

**Comment by aeuu** [comment]
MIT/ISC are the most common licenses used in Node.js. (They are basically the same thing, but named differently. MIT may be a better choice if you're picking one of these two). They both allow anyone to use, modify, or distribute your code without limitation, but no warranty or liability is maintained.

LGPL/GLP/AGPL are copyleft licenses. They let people do almost anything with your code as long as it's distributed under the same license (so all forks or usages of your code will stay open source). LGPL is the most permissive of the three, while AGPL is the most restrictive. 

Not using a license inherently make's your code copyright.

**Comment by aeuu** [comment]
A good resource to picking a license is: https://choosealicense.com/
