### ISSUE TITLE
Some Chat History Bugs

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#18]
**Describe the bug**
### Bug 1
The chat history does not auto scroll down when chat messages are filled inside it.

### Bug 2
You can resize the chat to be almost non-visible.

**Expected behavior**
Chat history should auto scroll with messages.
Chat history should have a minimum and maximum resize limit.

**Screenshots**
![Image](https://i.gyazo.com/69d6f2fb8d37cebb14708748306089be.png)

**Comment by aeuu** [comment]
PR #21 has fixed the issues detailed in this issue.
