### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by steviegt6** [Valks-Games/io-game#2]
When I walk ontop of another client, our sprites interfere with each other. Perhaps you could draw one on top of the other?
![image](https://user-images.githubusercontent.com/27323911/65921965-9b353380-e398-11e9-8257-7eba506db092.png)

**Comment by aeuu** [comment]
Depending on the point of the game it may be a good idea to add collision detection.

**Comment by steviegt6** [comment]
Yeah, collision, in general, may also be nice.

**Comment by valkyrienyanko** [comment]
Don't fully understand this, perhaps someone else could implement it.

https://p5js.org/examples/motion-bouncy-bubbles.html
