### ISSUE TITLE
p5.js Alternatives

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#20]
Someone suggested using Unity and exporting to WEBGL.

I can see some pros and cons to this.

Pros
- Support for more complex 3D models, and bone systems. (p5.js only supports `.obj` `.stl` models, never looked into `.stl` yet, don't know if it has what I'm looking for)
- Post Processing

Cons
- Have to deal with Unity performance bugs. (or is this just me?)

----------------
Or maybe we should convert from p5.js to three.js https://github.com/mrdoob/three.js/
Someone even made a post processing addon for it https://github.com/vanruesc/postprocessing

**Comment by valkyrienyanko** [comment]
Just look at how cool this is. https://threejs.org/examples/#webgl_animation_skinning_blending

**Comment by aeuu** [comment]
I would not suggest migrating to Unity as this is meant to be a lightweight .io game rather than a full three dimensional game with fancy graphics and models. p5.js or three.js would be a good choice.

**Comment by valkyrienyanko** [comment]
Or maybe it secretly is. 😛

**Comment by valkyrienyanko** [comment]
Regardless, three.js is everything Unity has as far as I'm concerned.

**Comment by valkyrienyanko** [comment]
three.js is hard to master, we stick with p5.js
