### ISSUE TITLE
Performance Limitations

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#22]
What are the performance limitations of three.js vs Unity vs Unreal?

**Comment by steviegt6** [comment]
I think the most obvious thing is that three.js is limited to JavaScript and in this case, the limitations of the average user's browser. Unity and Unreal have much more freedom and a gamespace.

**Comment by valkyrienyanko** [comment]
https://www.quora.com/How-powerful-can-WebGL-games-be-in-terms-of-graphics

**Comment by valkyrienyanko** [comment]
http://webglsamples.org/aquarium/aquarium.html
