### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#28]
`yarn lint` and `yarn lint:fix` compile successfully but do not do anything nor give any useful feedback?

![Preview](https://i.gyazo.com/e21d72dc324fe2e48f6f7a24f382a7f8.png)

**Comment by JohnTendik** [comment]
Is this still an issue? It worked for me

![image](https://user-images.githubusercontent.com/4714913/67730461-84035900-f9cb-11e9-83b5-81ad15ce80c9.png)

and running `yarn lint:fix` did fix the spacing issue.

**Comment by valkyrienyanko** [comment]
Earlier I was trying to figure out why the linter was not linting the public folder and then I discovered the `.eslintignore` file. I removed the public folder from the ignore list and found out that eslint was now complaining that all p5.js functions were undefined. So I installed a p5.js config and now everything seems to work. I'll commit the changes so you can see as well. Right now I'm just trying to suppress the yarn error on eslint execution. ![Preview](https://i.gyazo.com/390809c20e4c641250dc2b6da49d3b28.png)

**Comment by valkyrienyanko** [comment]
Not that it matters that yarn is spitting out errors whenever you use the linter.
